# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed91683d7ecc45b559df90e0b534541523bd71ee7da8d7b5606a214c1472d98d942b451a9cb4dde7b7edc769c7212c34af249fcdcf08a282b8d29a309905be58

test:
  secret_key_base: ef5938a76327d6b3fa2c12cf480b7c6b9f9c454fc7aaad0b994e8dffd14e99f442643cda82f92771a17e869ed339816a733d29634d23bd3b370d5c40f13199c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
